DROP TABLE STUDENT;
CREATE TABLE STUDENT
    (RollNo INT(10), Name VARCHAR(20), Age INT(10), Mark INT(10));
INSERT INTO STUDENT (RollNo, Name, Age, Mark) 
    VALUES (1,'Anil',22,45), (2,'Manu',25,40), (3,'Lalu',23,43);
SELECT * FROM STUDENT;
SELECT AVG(MARK) AS AVERAGE FROM STUDENT;
SELECT MIN(AGE) AS MINIMUM_AGE FROM STUDENT;
SELECT SUM(MARK) AS TOTAL FROM STUDENT;
SELECT COUNT(*) AS NO_OF_ROWS FROM STUDENT;
