CREATE TABLE STUDENT
    (RollNo INT(10), Name VARCHAR(20), Age INT(10), Mark INT(10));
INSERT INTO STUDENT (RollNo, Name, Age, Mark) 
    VALUES (1,'Anil',22,45), (2,'Manu',25,40), (3,'Lalu',23,43);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT ORDER BY NAME;
SELECT * FROM STUDENT ORDER BY MARK DESC;
SELECT * FROM STUDENT WHERE NAME LIKE "A%";
SELECT * FROM STUDENT WHERE NAME LIKE "%nu";